---
language: node_js

node_js:
  - "0.11"
  - "0.10"
  - "0.12"

sudo: false

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "npm install -g bower"
env:
  - TEST_DIR=client
  - TEST_DIR=server

script: cd $TEST_DIR && npm install && bower install && npm test